const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{backgrdFase1: 0},
	{Sólido: 0},
	{gramaFase1: 0},
	{sensor_buraco: 0},
	{Direcao: 0},
	{Plataforma: 0},
	{Esqueleto1: 0},
	{DirecaoEsqueleto2: 0},
	{Esqueleto2: 0},
	{Esqueleto3: 0},
	{DirecaoLobi: 0},
	{Lobisomen: 0},
	{Lobisomen2: 0},
	{Arqueiro: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{Flecha: 0},
	{sensor_patrulha_direita: 0},
	{sensor_patrulha_direita2: 0},
	{sensor_patrulha_direita3: 0},
	{sensor_patrulha_direita4: 0},
	{sensor_patrulha_esquerda: 0},
	{sensor_patrulha_esquerda2: 0},
	{sensor_patrulha_esquerda3: 0},
	{sensor_patrulha_esquerda4: 0},
	{sensorFase1: 0},
	{AreaAlerta: 0},
	{backgrdInicio: 0},
	{Iniciar: 0},
	{backgrdFase3: 0},
	{chaoFase2: 0},
	{AlvoX: 0},
	{RestritoAoLayout: 0},
	{Malakor: 0},
	{vidasBoss: 0},
	{backgrdGameOver: 0},
	{Iniciar2: 0},
	{gameOver: 0},
	{jogador1: 0},
	{jogador2: 0},
	{fireball: 0},
	{NomeJogador1: 0},
	{NomeJogador2: 0},
	{vidas1: 0},
	{vidas2: 0},
	{Iniciar3: 0},
	{sucesso: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Fam_Jogadores: 0},
	{Fam_Inimigos: 0},
	{VidasJogador1: 0},
	{VidasJogador2: 0},
	{vidasboss: 0}
];

self.InstanceType = {
	backgrdFase1: class extends self.ITiledBackgroundInstance {},
	gramaFase1: class extends self.ISpriteInstance {},
	sensor_buraco: class extends self.ISpriteInstance {},
	Esqueleto1: class extends self.ISpriteInstance {},
	Esqueleto2: class extends self.ISpriteInstance {},
	Esqueleto3: class extends self.ISpriteInstance {},
	Lobisomen: class extends self.ISpriteInstance {},
	Lobisomen2: class extends self.ISpriteInstance {},
	Arqueiro: class extends self.ISpriteInstance {},
	Flecha: class extends self.ISpriteInstance {},
	sensor_patrulha_direita: class extends self.ISpriteInstance {},
	sensor_patrulha_direita2: class extends self.ISpriteInstance {},
	sensor_patrulha_direita3: class extends self.ISpriteInstance {},
	sensor_patrulha_direita4: class extends self.ISpriteInstance {},
	sensor_patrulha_esquerda: class extends self.ISpriteInstance {},
	sensor_patrulha_esquerda2: class extends self.ISpriteInstance {},
	sensor_patrulha_esquerda3: class extends self.ISpriteInstance {},
	sensor_patrulha_esquerda4: class extends self.ISpriteInstance {},
	sensorFase1: class extends self.ISpriteInstance {},
	AreaAlerta: class extends self.ISpriteInstance {},
	backgrdInicio: class extends self.ITiledBackgroundInstance {},
	Iniciar: class extends self.ITextInstance {},
	backgrdFase3: class extends self.ITiledBackgroundInstance {},
	chaoFase2: class extends self.ISpriteInstance {},
	Malakor: class extends self.ISpriteInstance {},
	vidasBoss: class extends self.ITextInstance {},
	backgrdGameOver: class extends self.ITiledBackgroundInstance {},
	Iniciar2: class extends self.ITextInstance {},
	gameOver: class extends self.ITextInstance {},
	jogador1: class extends self.ISpriteInstance {},
	jogador2: class extends self.ISpriteInstance {},
	fireball: class extends self.ISpriteInstance {},
	NomeJogador1: class extends self.ITextInstance {},
	NomeJogador2: class extends self.ITextInstance {},
	vidas1: class extends self.ITextInstance {},
	vidas2: class extends self.ITextInstance {},
	Iniciar3: class extends self.ITextInstance {},
	sucesso: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Fam_Jogadores: class extends self.ISpriteInstance {},
	Fam_Inimigos: class extends self.ISpriteInstance {}
}